name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
  comment:
      runs-on: ubuntu-latest

      steps:
      - uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          message: "Gentle reminder:\n* Did you go through all of the troubleshooting steps outlined in README.md?"
